remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [JAXB]
description: [Java XML binding implementation]

links:
  source: https://github.com/eclipse-ee4j/jaxb-ri
  javadocs: javadocs/index.html
  download: https://github.com/eclipse-ee4j/jaxb-ri/releases/tag/2.3.2-RI
  mailinglist: https://accounts.eclipse.org/mailing-list/jaxb-dev
  faq: FAQ